FROM ubuntu
CMD ["Anonymous"]
ENTRYPOINT ["echo", "My Name is "]

# 결과 :
# My Name is  Anonymous

# docker run -it cmd.entrypoint Elice
# 라고 한다면 결과 :
# My Name is  Elice

# CMD에 뭘 했던간에 (앞서 했던 exec든 ..) ENTRYPOINT와 함꼐 사용하면 무조건 파라미터로 인식이 된다.